# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=50, unique=True, verbose_name='Protocol Number')),
                ('expense_type', models.CharField(choices=[('CONSULTATION', 'Medical Consultation'), ('EXAM', 'Medical Exam'), ('MEDICATION', 'Medication'), ('HOSPITALIZATION', 'Hospitalization'), ('SURGERY', 'Surgery'), ('THERAPY', 'Therapy'), ('OTHER', 'Other')], max_length=20, verbose_name='Expense Type')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('service_description', models.TextField(verbose_name='Service Description')),
                ('provider_name', models.CharField(max_length=200, verbose_name='Provider Name')),
                ('provider_cnpj_cpf', models.CharField(max_length=14, verbose_name='Provider CNPJ/CPF')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Requested Amount')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Amount')),
                ('bank_details', models.JSONField(verbose_name='Bank Details')),
                ('status', models.CharField(choices=[('IN_ANALYSIS', 'In Analysis'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('DENIED', 'Denied'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='IN_ANALYSIS', max_length=20, verbose_name='Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('analysis_date', models.DateTimeField(blank=True, null=True, verbose_name='Analysis Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('denial_reason', models.TextField(blank=True, verbose_name='Denial Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Reimbursement Request',
                'verbose_name_plural': 'Reimbursement Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice/Receipt'), ('PRESCRIPTION', 'Medical Prescription'), ('REPORT', 'Medical Report'), ('RECEIPT', 'Payment Receipt'), ('OTHER', 'Other')], max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='reimbursements/documents/', verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reimbursements.reimbursementrequest')),
            ],
            options={
                'verbose_name': 'Reimbursement Document',
                'verbose_name_plural': 'Reimbursement Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
