# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('UPDATE', 'System Update'), ('ANNOUNCEMENT', 'Announcement'), ('HEALTH_TIP', 'Health Tip')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('target_all', models.BooleanField(default=True, verbose_name='Target All')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_companies', models.ManyToManyField(blank=True, related_name='system_messages', to='beneficiaries.company')),
                ('target_plans', models.ManyToManyField(blank=True, related_name='system_messages', to='beneficiaries.healthplan')),
            ],
            options={
                'verbose_name': 'System Message',
                'verbose_name_plural': 'System Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GUIDE_AUTHORIZATION', 'Guide Authorization'), ('REIMBURSEMENT_STATUS', 'Reimbursement Status'), ('INVOICE_DUE', 'Invoice Due'), ('SYSTEM_MESSAGE', 'System Message'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('APPOINTMENT_REMINDER', 'Appointment Reminder')], max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push Sent')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Push Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, verbose_name='Device Type')),
                ('token', models.CharField(max_length=500, verbose_name='Push Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'unique_together': {('beneficiary', 'token')},
            },
        ),
    ]
