# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('PRESCRIPTION', 'Medical Prescription'), ('EXAM_REQUEST', 'Exam Request'), ('REPORT', 'Medical Report'), ('IMAGE', 'Medical Image'), ('OTHER', 'Other')], max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to='guides/attachments/', verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Guide Attachment',
                'verbose_name_plural': 'Guide Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('authorized_quantity', models.IntegerField(default=0, verbose_name='Authorized Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Guide Procedure',
                'verbose_name_plural': 'Guide Procedures',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='TUSS Code')),
                ('name', models.CharField(max_length=200, verbose_name='Procedure Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('requires_authorization', models.BooleanField(default=True, verbose_name='Requires Authorization')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TISSGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_type', models.CharField(choices=[('SP_SADT', 'SP/SADT - Support Services'), ('CONSULTATION', 'Consultation'), ('HOSPITALIZATION', 'Hospitalization'), ('EMERGENCY', 'Emergency')], max_length=20, verbose_name='Guide Type')),
                ('guide_number', models.CharField(max_length=50, unique=True, verbose_name='Guide Number')),
                ('protocol_number', models.CharField(max_length=50, unique=True, verbose_name='Protocol Number')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Authorization Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_ANALYSIS', 'In Analysis'), ('AUTHORIZED', 'Authorized'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Status')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('requesting_physician_name', models.CharField(max_length=200, verbose_name='Requesting Physician')),
                ('requesting_physician_crm', models.CharField(max_length=20, verbose_name='CRM')),
                ('denial_reason', models.TextField(blank=True, verbose_name='Denial Reason')),
                ('guide_pdf', models.FileField(blank=True, null=True, upload_to='guides/pdf/', verbose_name='Guide PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='beneficiaries.beneficiary')),
                ('procedures', models.ManyToManyField(related_name='guides', through='guides.GuideProcedure', to='guides.procedure')),
            ],
            options={
                'verbose_name': 'TISS Guide',
                'verbose_name_plural': 'TISS Guides',
                'ordering': ['-request_date'],
            },
        ),
    ]
