# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissguide',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='providers.accreditedprovider'),
        ),
        migrations.AddField(
            model_name='guideprocedure',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_procedures', to='guides.tissguide'),
        ),
        migrations.AddField(
            model_name='guideprocedure',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_procedures', to='guides.procedure'),
        ),
        migrations.AddField(
            model_name='guideattachment',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='guides.tissguide'),
        ),
    ]
