# Generated by Django 4.2.11 on 2025-10-29 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='Nome da Vacina')),
                ('dose', models.CharField(blank=True, max_length=50, verbose_name='Dose')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('date_administered', models.DateField(verbose_name='Data de Aplicação')),
                ('next_dose_date', models.DateField(blank=True, null=True, verbose_name='Próxima Dose')),
                ('provider_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Local')),
                ('professional_name', models.CharField(blank=True, max_length=255, verbose_name='Profissional Responsável')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='beneficiaries.beneficiary', verbose_name='Beneficiário')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='providers.accreditedprovider', verbose_name='Local de Aplicação')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
                'db_table': 'vaccinations',
                'ordering': ['-date_administered', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('CONSULTATION', 'Consulta'), ('EXAM', 'Exame'), ('SURGERY', 'Cirurgia'), ('HOSPITALIZATION', 'Internação'), ('EMERGENCY', 'Emergência'), ('PROCEDURE', 'Procedimento'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Registro')),
                ('date', models.DateField(verbose_name='Data')),
                ('provider_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Prestador')),
                ('professional_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Profissional')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico/CID')),
                ('description', models.TextField(verbose_name='Descrição/Observações')),
                ('prescribed_medications', models.TextField(blank=True, verbose_name='Medicamentos Prescritos')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Anexos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='beneficiaries.beneficiary', verbose_name='Beneficiário')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='providers.accreditedprovider', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Registro de Saúde',
                'verbose_name_plural': 'Registros de Saúde',
                'db_table': 'health_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
