# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Specialty Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccreditedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('CLINIC', 'Clinic'), ('LABORATORY', 'Laboratory'), ('HOSPITAL', 'Hospital'), ('PHARMACY', 'Pharmacy')], max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Trade Name')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=8, verbose_name='ZIP Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('accepts_telemedicine', models.BooleanField(default=False, verbose_name='Accepts Telemedicine')),
                ('accepts_emergency', models.BooleanField(default=False, verbose_name='Accepts Emergency')),
                ('working_hours', models.JSONField(default=dict, verbose_name='Working Hours')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Rating')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Total Reviews')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(related_name='providers', to='providers.specialty', verbose_name='Specialties')),
            ],
            options={
                'verbose_name': 'Accredited Provider',
                'verbose_name_plural': 'Accredited Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to='beneficiaries.beneficiary')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.accreditedprovider')),
            ],
            options={
                'verbose_name': 'Provider Review',
                'verbose_name_plural': 'Provider Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'beneficiary')},
            },
        ),
    ]
