# Generated by Django 4.2.11 on 2025-10-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.CharField(max_length=7, verbose_name='Reference Month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('barcode', models.CharField(max_length=100, verbose_name='Barcode')),
                ('digitable_line', models.CharField(max_length=100, verbose_name='Digitable Line')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='Invoice PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-reference_month', '-due_date'],
                'unique_together': {('beneficiary', 'reference_month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('BANK_SLIP', 'Bank Slip'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('PIX', 'PIX')], max_length=20, verbose_name='Payment Method')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='financial.invoice')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Period')),
                ('consultations_count', models.IntegerField(default=0, verbose_name='Consultations')),
                ('exams_count', models.IntegerField(default=0, verbose_name='Exams')),
                ('procedures_count', models.IntegerField(default=0, verbose_name='Procedures')),
                ('hospitalizations_count', models.IntegerField(default=0, verbose_name='Hospitalizations')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('copayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Copayment Amount')),
                ('usage_details', models.JSONField(default=list, verbose_name='Usage Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Usage History',
                'verbose_name_plural': 'Usage Histories',
                'ordering': ['-period'],
                'unique_together': {('beneficiary', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TaxStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Paid')),
                ('deductible_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deductible Amount')),
                ('monthly_breakdown', models.JSONField(default=dict, verbose_name='Monthly Breakdown')),
                ('statement_pdf', models.FileField(blank=True, null=True, upload_to='tax_statements/pdf/', verbose_name='Statement PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_statements', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Tax Statement',
                'verbose_name_plural': 'Tax Statements',
                'ordering': ['-year'],
                'unique_together': {('beneficiary', 'year')},
            },
        ),
    ]
