# Generated by Django 4.2.11 on 2025-10-29 01:17

import apps.uploads.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.uploads.models.upload_to, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('upload_type', models.CharField(choices=[('GUIDE_ATTACHMENT', 'Anexo de Guia'), ('REIMBURSEMENT_DOCUMENT', 'Documento de Reembolso'), ('PROFILE_PHOTO', 'Foto de Perfil'), ('PRESCRIPTION', 'Receita Médica'), ('MEDICAL_REPORT', 'Relatório Médico'), ('INVOICE', 'Nota Fiscal'), ('RECEIPT', 'Comprovante'), ('OTHER', 'Outro')], default='OTHER', max_length=50, verbose_name='Tipo de Upload')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Conteúdo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='beneficiaries.beneficiary', verbose_name='Beneficiário')),
            ],
            options={
                'verbose_name': 'Arquivo Enviado',
                'verbose_name_plural': 'Arquivos Enviados',
                'db_table': 'uploads_uploaded_file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
