# Generated by Django 4.2.11 on 2025-12-22 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.JSONField(verbose_name='Value')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SECURITY', 'Security'), ('NOTIFICATIONS', 'Notifications'), ('REPORTS', 'Reports'), ('INTEGRATION', 'Integration')], max_length=20, verbose_name='Category')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Is Sensitive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'admin_api_system_configuration',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('VIEWER', 'Viewer')], default='ADMIN', max_length=20, verbose_name='Role')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('login_count', models.IntegerField(default=0, verbose_name='Login Count')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_api_admin_profile',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Entity Type')),
                ('entity_id', models.IntegerField(verbose_name='Entity ID')),
                ('entity_repr', models.CharField(max_length=200, verbose_name='Entity Representation')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('session_id', models.CharField(blank=True, max_length=64, verbose_name='Session ID')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'admin_api_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin', 'timestamp'], name='admin_api_a_admin_i_eeb2d0_idx'), models.Index(fields=['entity_type', 'entity_id'], name='admin_api_a_entity__947d44_idx'), models.Index(fields=['timestamp'], name='admin_api_a_timesta_37dc94_idx')],
            },
        ),
    ]
