# Generated by Django 4.2.11 on 2025-10-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=8, verbose_name='ZIP Code')),
                ('beneficiary_type', models.CharField(choices=[('TITULAR', 'Titular'), ('DEPENDENT', 'Dependent')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('rg_document', models.FileField(blank=True, null=True, upload_to='documents/rg/')),
                ('cpf_document', models.FileField(blank=True, null=True, upload_to='documents/cpf/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('EXECUTIVE', 'Executive')], max_length=20, verbose_name='Plan Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Fee')),
                ('coverage_details', models.JSONField(default=dict, verbose_name='Coverage Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Plan',
                'verbose_name_plural': 'Health Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Card Number')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('qr_code_data', models.TextField(verbose_name='QR Code Data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_cards', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Digital Card',
                'verbose_name_plural': 'Digital Cards',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='beneficiaries.company'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='health_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='beneficiaries.healthplan'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='beneficiaries.beneficiary', verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
