# Generated by Django 4.2.11 on 2025-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='ZIP Code'),
        ),
    ]
