# Generated by Django 4.2.11 on 2025-11-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalCard',
        ),
    ]
