# Generated by Django 4.2.11 on 2026-01-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0007_materialize_oracle_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completed'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onboarding Completed At'),
        ),
    ]
